name: roya
description: "رؤية ٣٤ (Roya34) - Mixed reality sports fan experience"

# Prevent accidental publishing to pub.dev
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  camera: ^0.10.5+5
  permission_handler: ^11.0.1
  video_player: ^2.8.1
  google_fonts: ^6.2.1
  http: ^1.1.2
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
